import type { CargoItem, Resource, RunModifier, RunQuest } from "./gameTypes";

// ─── Constants ──────────────────────────────────────────────────────────────
export const TILE = 32;

export const SPEECH_POOLS: Record<string, string[]> = {
  fudder: [
    "ICP is dead 💀",
    "wen pump???",
    "this is a ponzi",
    "ngmi",
    "no utility",
    "ser this is a casino",
    "have fun staying poor",
    "just wait for the dip",
    "wen whitepaper???",
    "have fun staying poor ser",
    "no devs no price",
    "rugpull incoming bro",
    "anon team red flag",
    "no use case lmao",
    "just a meme coin bro",
    "chain is centralised ser",
    "Your chain is centralized! Dom controls everything! 🤤",
    "Dom just pre-mined this whole tunnel! Wake up sheeple!",
    "I have a 200-page document proving ICP is a scam! DM me!",
    "The tokenomics literally say rugpull in the footnotes! READ IT!",
    "I counted 47 red flags in the whitepaper alone. DM me for the thread. 🧵",
  ],
  sec_agent: [
    "UNREGISTERED SEC.",
    "YOU OWE TAXES",
    "HALT MINER",
    "SUBPOENA ISSUED",
    "FREEZE CRIMINAL",
    "LICENSE AND PERMIT PLEASE",
    "WE'VE BEEN WATCHING YOU",
    "FREEZE — SECURITIES VIOLATION",
    "YOU'RE ALL GETTING DELISTED",
    "COMPLAINT FILED",
    "CEASE EXCAVATION OPERATIONS",
    "THIS MINE IS UNDER AUDIT",
    "ALL TOKENS UNREGISTERED",
    "REPORT TO HEADQUARTERS",
    "MINING WITHOUT A LICENSE",
    "WE'VE CLASSIFIED THIS ORE AS AN UNREGISTERED SECURITY!",
    "YOU NEED 14 LICENSES TO DRILL PAST 80M!",
    "STOP RESISTING — THIS DRILL IS EXHIBIT A!",
    "EVERY ORE IN YOUR CARGO IS EVIDENCE!",
    "WE'VE NOTIFIED INTERPOL ABOUT YOUR DIGGING ACTIVITIES!",
  ],
  btc_maxi: [
    "HAVE FUN STAYING POOR",
    "JUST BUY BTC",
    "DIGITAL GOLD ONLY",
    "ICP? LOL",
    "LASER EYES ACTIVATED",
    "NOCOINERS DESERVE THIS",
    "JUST STACK SATS",
    "NUMBER GO UP TECH",
    "LIGHTNING NETWORK IS FINE",
    "ALTCOINS ARE SCAMS",
    "BITCOIN IS THE ONLY CHAIN",
    "1 BTC = 1 BTC ALWAYS",
    "YOUR CHAIN WILL FAIL",
    "PROOF OF WORK ONLY",
    "LIGHTNING FIXES EVERYTHING",
    "HAVE FUN STAYING POOR DIGGING ALTCOINS!",
    "SATOSHI NEVER DUG BELOW 50M FOR A REASON!",
    "PROOF OF WORK OR GO HOME! NGMI!",
    "YOUR ORE WILL NEVER BE DIGITAL GOLD! EVER!",
    "I MINED BITCOIN IN 2009. YOU MINE MEME COINS. WE ARE NOT THE SAME.",
  ],
  rug_puller: [
    "nothing to see here",
    "nice ore you have",
    "trust me bro",
    "anon wallet only",
    "thanks for the alpha",
    "wen refund lol",
    "smart contract audit? never heard of it",
    "thanks for the liquidity",
    "smart contract malfunction lol",
    "it was a feature not a bug",
    "100x guaranteed ser",
    "the team is fully doxxed (they aren't)",
    "liquidity locked (it wasn't)",
    "roadmap fully delivered (lol)",
    "presale was fair launch (it wasn't)",
    "this mine is just a liquidity drain!",
    "the devs are already on a beach in Dubai 🏖️",
    "soft rug incoming — check the contract ser",
    "I pulled rugs before it was fashionable. You're welcome.",
    "New mine just dropped! Definitely not a honeypot! (It is a honeypot)",
  ],
  whale_dumper: [
    "DUMPING NOW",
    "sell the news",
    "exit liquidity",
    "bye bye price",
    "oops my finger slipped",
    "just taking profits ser",
    "market manipulation? i prefer price discovery",
    "just rebalancing my portfolio",
    "small correction incoming",
    "ngmi hodlers",
    "buy my bags please",
    "paper hands needed",
    "mass liquidation incoming",
    "who wants my exit liquidity",
    "thanks for the pump, time to dump",
    "I just shorted your entire cargo!",
    "Whales set the price. Miners suffer the price.",
    "flash crash activated — enjoy the liquidation, ser",
    "I moved $40M out of ICP last Tuesday. Did you notice? You did now. 🐋",
    "Dump it all. Then buy back cheaper. That's not manipulation. That's strategy.",
  ],
  nns_voter: [
    "Governance says NO!",
    "Motion rejected!",
    "You need more voting power!",
    "The NNS has spoken!",
    "PROPOSAL DENIED!",
    "Insufficient voting neurons!",
    "Your drilling violates protocol!",
    "Vote failed! Stake more ICP!",
  ],
  governance_troll: [
    "Your proposal is SPAM!",
    "I'll vote NO forever!",
    "Governance is MY weapon!",
    "Nobody reads the proposals!",
    "REJECTED! REJECTED! REJECTED!",
    "I have 10 million neurons just for voting NO!",
    "The NNS is my playground, miner!",
  ],
  head_fudder: [
    "YOU SHALL NOT PASS",
    "THE BOB IS MINE",
    "TURN BACK MINER",
    "THE FUDDING IS ETERNAL",
    "THE GENESIS BLOCK BELONGS TO FUDDERS",
    "155M IS THE MAXIMUM FUD",
    "YOUR DRILL CANNOT PIERCE ETERNAL DOUBT",
    "NGMI NGMI NGMI",
    "THE PROTOCOL IS COMPROMISED",
    "YOUR DRILL IS NOTHING AGAINST ETERNAL FUD",
    "I HAVE BEEN WAITING 3 YEARS FOR THIS MOMENT",
  ],
};

// ─── Run Modifiers ──────────────────────────────────────────────────────────────
export const MODIFIER_POOL: RunModifier[] = [
  {
    id: "fuel_tax",
    label: "⛽ FUEL TAX",
    description:
      "Fuel drains 1.5× faster but all ores sell for 1.8× their value.",
    effect: "fuel_tax",
  },
  {
    id: "bounty_hunters",
    label: "🎯 BOUNTY HUNTERS",
    description: "Antagonists are relentless, but each defeat drops +150 BOB.",
    effect: "bounty_hunters",
  },
  {
    id: "rich_seam",
    label: "💎 RICH SEAM",
    description: "Rare ores spawn 2× more often in the deep layers.",
    effect: "rich_seam",
  },
  {
    id: "black_market",
    label: "🕶 BLACK MARKET",
    description: "All shop prices discounted 25%. No questions asked.",
    effect: "black_market",
  },
  {
    id: "heavy_load",
    label: "🏗 HEAVY LOAD",
    description: "+50% cargo capacity but engine speed reduced 20%.",
    effect: "heavy_load",
  },
  {
    id: "cursed_drill",
    label: "💀 CURSED DRILL",
    description: "Mining damages hull 2×, but drill operates at 2× speed.",
    effect: "cursed_drill",
  },
  {
    id: "explorer_map",
    label: "🗺 EXPLORER MAP",
    description:
      "Minimap fully revealed from the very start. No blind drilling.",
    effect: "explorer_map",
  },
  {
    id: "veteran_kit",
    label: "🎖 VETERAN KIT",
    description: "Start with +50 BOB and 10% extra fuel already in the tank.",
    effect: "veteran_kit",
  },
  {
    id: "fudder_swarm",
    label: "😱 FUDDER SWARM",
    description:
      "Fudders spawn 2× more often, but ALL antagonist BOB drops are doubled.",
    effect: "fudder_swarm",
  },
  {
    id: "smooth_ride",
    label: "🛤 SMOOTH RIDE",
    description: "No fuel cost when moving horizontally on flat ground.",
    effect: "smooth_ride",
  },
  {
    id: "generous_protocol",
    label: "🎁 GENEROUS PROTOCOL",
    description:
      "Start with a free Cargo upgrade and 200 BOB. No strings attached. Probably.",
    effect: "generous_protocol",
  },
  {
    id: "hostile_underground",
    label: "☠️ HOSTILE UNDERGROUND",
    description:
      "Antagonists deal 2x damage but drop 3x BOB on defeat. High risk, high reward.",
    effect: "hostile_underground",
  },
  {
    id: "ghost_protocol",
    label: "👻 GHOST PROTOCOL",
    description:
      "Antagonists cannot see or attack you — but the shop scanner is jammed. Sell prices -20%.",
    effect: "ghost_protocol",
  },
  {
    id: "turbo_drill",
    label: "⚡ TURBO DRILL",
    description:
      "Drill speed +50% but hull takes 2x damage from rock impacts. Speed at a price.",
    effect: "turbo_drill",
  },
  {
    id: "overclock",
    label: "🔥 OVERCLOCK",
    description: "Drill 2x faster, overheat 2x faster. Speed costs.",
    effect: "drill_speed_2x_heat_2x",
  },
  {
    id: "seismic_zone",
    label: "🌋 SEISMIC ZONE",
    description: "Earthquakes every 45s — ore spawns 1.5x richer.",
    effect: "earthquake_frequent_ore_rich",
  },
  {
    id: "diplomatic_immunity",
    label: "🤝 DIPLOMATIC IMMUNITY",
    description: "NPCs give 20% discounts, antagonists deal 50% less damage.",
    effect: "diplomatic_immunity",
  },
  {
    id: "ore_rush",
    label: "⚡ ORE RUSH",
    description:
      "Drill speed +50%, but all ore sell values -20%. Speed over profit.",
    effect: "ore_rush",
  },
  {
    id: "bargain_hunt",
    label: "🛒 BARGAIN HUNT",
    description:
      "All shop prices -25%, but fuel drains 20% faster. Shop smart.",
    effect: "bargain_hunt",
  },
  {
    id: "elite_escort",
    label: "💀 ELITE ESCORT",
    description: "Antagonists spawn 2x as often, but each defeat drops 40 BOB.",
    effect: "elite_escort",
  },
];

export const JERRY_QUEST_POOL: Array<
  Omit<RunQuest, "id" | "progress" | "completed">
> = [
  {
    npcId: "jerry",
    description: "Mine 3 Dom's Dust",
    type: "mine_ore",
    targetOre: 20,
    goal: 3,
    reward: "+100 BOB",
  },
  {
    npcId: "jerry",
    description: "Mine 2 NNS Nuggets",
    type: "mine_ore",
    targetOre: 22,
    goal: 2,
    reward: "+150 BOB",
  },
  {
    npcId: "jerry",
    description: "Mine 1 Banfield Ore",
    type: "mine_ore",
    targetOre: 23,
    goal: 1,
    reward: "+200 BOB",
  },
  {
    npcId: "jerry",
    description: "Mine 1 Dragginz Crystal",
    type: "mine_ore",
    targetOre: 24,
    goal: 1,
    reward: "+250 BOB",
  },
  {
    npcId: "jerry",
    description: "Mine 2 ckBTC Chunks",
    type: "mine_ore",
    targetOre: 25,
    goal: 2,
    reward: "+300 BOB",
  },
  {
    npcId: "jerry",
    description: "Reach depth 30m",
    type: "reach_depth",
    goal: 30,
    reward: "+fuel",
  },
  {
    npcId: "jerry",
    description: "Reach depth 60m",
    type: "reach_depth",
    goal: 60,
    reward: "+hull repair",
  },
  {
    npcId: "jerry",
    description: "Reach depth 100m",
    type: "reach_depth",
    goal: 100,
    reward: "+500 BOB",
  },
  {
    npcId: "jerry",
    description: "Defeat 2 antagonists",
    type: "defeat_antagonists",
    goal: 2,
    reward: "+hull repair",
  },
  {
    npcId: "jerry",
    description: "Defeat 5 antagonists",
    type: "defeat_antagonists",
    goal: 5,
    reward: "+300 BOB",
  },
  {
    npcId: "jerry",
    description: "Haul cargo worth 500 BOB",
    type: "cargo_value",
    goal: 500,
    reward: "+200 BOB",
  },
  {
    npcId: "jerry",
    description: "Haul cargo worth 2000 BOB",
    type: "cargo_value",
    goal: 2000,
    reward: "+800 BOB",
  },
  {
    npcId: "jerry",
    description: "Find 1 lore room",
    type: "find_lore_rooms",
    goal: 1,
    reward: "+150 BOB",
  },
  {
    npcId: "jerry",
    description: "Find 2 lore rooms",
    type: "find_lore_rooms",
    goal: 2,
    reward: "+350 BOB",
  },
  {
    npcId: "jerry",
    description: "Return with full cargo",
    type: "cargo_value",
    goal: 1000,
    reward: "+drill upgrade",
  },
  {
    npcId: "jerry",
    description: "Collect 3 different ore types in one run",
    type: "collect_ore_types",
    goal: 3,
    reward: "+300 BOB",
  },
  {
    npcId: "jerry",
    description: "Survive an earthquake without taking damage",
    type: "survive_earthquake",
    goal: 1,
    reward: "+fuel",
  },
  {
    npcId: "jerry",
    description: "Reach depth 80m",
    type: "reach_depth",
    goal: 80,
    reward: "+500 BOB",
  },
  {
    npcId: "jerry",
    description: "Sell 1000 BOB worth of cargo in a single trip",
    type: "sell_trip_value",
    goal: 1000,
    reward: "+drill upgrade",
  },
  {
    npcId: "jerry",
    description: "Defeat a BTC Maxi",
    type: "defeat_btc_maxi",
    goal: 1,
    reward: "+400 BOB",
  },
  {
    npcId: "jerry",
    description: "👻 Encounter the Ghost Miner deep underground",
    type: "ghost_miner_encounter",
    goal: 1,
    reward: "+800 BOB",
  },
];

export const NPC_QUEST_POOL: Array<
  Omit<RunQuest, "id" | "progress" | "completed">
> = [
  {
    npcId: "dom",
    description: "Reach depth 80m (Dom's orders)",
    type: "reach_depth",
    goal: 80,
    reward: "+drill upgrade",
  },
  {
    npcId: "bob",
    description: "Find 3 secret lore rooms (BOB leads the way)",
    type: "find_lore_rooms",
    goal: 3,
    reward: "+400 BOB",
  },
  {
    npcId: "whale",
    description: "Return with 1500+ BOB cargo value (The Whale is watching)",
    type: "cargo_value",
    goal: 1500,
    reward: "+600 BOB",
  },
];

export const MAP_W = 80;
export const MAP_H = 160;
export const GRAVITY = 0.4;
export const PLAYER_SPEED = 3;
export const DRILL_BASE_TIME = 38;

// Shop building position (world tiles)
export const SHOP_X = 2;
export const SHOP_W = 4;
export const SHOP_Y = 2;
export const SHOP_H = 3;

// ─── Tile Types ──────────────────────────────────────────────────────────────
export const T = {
  EMPTY: 0,
  DIRT: 1,
  STONE: 2,
  HARD_ROCK: 3,
  BOB_DUST: 20,
  BOB_FLECK: 21,
  BOB_FRAGMENT: 22,
  BOB_SHARD: 23,
  BOB_CHIP: 24,
  BOB_CRYSTAL: 25,
  BOB_CORE: 26,
  BOB_INGOT: 27,
  BOB_VEIN: 28,
  BOB_SEAM: 29,
  NNS_TOKEN: 41,
  CHAIN_FUSION: 42,
  DRAGGINZ_SCALE: 43,
  BOB_GENESIS: 99,
  CAVE_IN: 30,
  GAS_POCKET: 31,
  WATER_TILE: 32,
  TREASURE_CHEST: 33,
  LAVA_TILE: 34,
  CRYSTAL_WALL: 35,
  LORE_ROOM: 40,
  SERAPH_TOKEN: 44,
  VOID_SHARD: 45,
  DEGEN_CRYSTAL: 46,
  LAVA_TUBE: 47,
  QUANTUM_BOB: 48,
} as const;

export const RESOURCES: Record<number, Resource> = {
  [T.BOB_DUST]: {
    name: "Dom's Dust",
    era: "Where it all began",
    value: 8,
    weight: 1,
    color: "#fbbf24",
    hardness: 0.8,
    depth: 0,
  },
  [T.BOB_FLECK]: {
    name: "Cycle Shard",
    era: "Burns fast, digs faster",
    value: 25,
    weight: 1,
    color: "#22d3ee",
    hardness: 1.0,
    depth: 10,
  },
  [T.BOB_FRAGMENT]: {
    name: "NNS Nugget",
    era: "The community voted to bury this here",
    value: 65,
    weight: 2,
    color: "#3b82f6",
    hardness: 1.2,
    depth: 25,
  },
  [T.BOB_SHARD]: {
    name: "Banfield Ore",
    era: "Found wherever there's a camera and an internet connection",
    value: 160,
    weight: 2,
    color: "#f97316",
    hardness: 1.4,
    depth: 45,
  },
  [T.BOB_CHIP]: {
    name: "Dragginz Crystal",
    era: "Rare, mysterious, probably has lore",
    value: 250,
    weight: 3,
    color: "#a855f7",
    hardness: 1.6,
    depth: 65,
  },
  [T.BOB_CRYSTAL]: {
    name: "ckBTC Chunk",
    era: "Bitcoin wished it could dig this deep",
    value: 600,
    weight: 3,
    color: "#f59e0b",
    hardness: 1.8,
    depth: 85,
  },
  [T.BOB_CORE]: {
    name: "SNS Sliver",
    era: "A tiny piece of a DAO nobody reads the proposals for",
    value: 1400,
    weight: 4,
    color: "#ef4444",
    hardness: 2.0,
    depth: 100,
  },
  [T.BOB_INGOT]: {
    name: "OpenChat Ore",
    era: "Mined through endless group messages",
    value: 3000,
    weight: 4,
    color: "#22c55e",
    hardness: 2.2,
    depth: 115,
  },
  [T.BOB_VEIN]: {
    name: "BOB Seam",
    era: "The meme coin that ate ICP's fees",
    value: 6500,
    weight: 5,
    color: "#fde047",
    hardness: 2.5,
    depth: 130,
  },
  [T.BOB_SEAM]: {
    name: "The Singularity Seam",
    era: "DFINITY said it's coming. Still waiting.",
    value: 12000,
    weight: 6,
    color: "#c084fc",
    hardness: 2.8,
    depth: 145,
  },
  [T.NNS_TOKEN]: {
    name: "NNS Token",
    era: "The governance token that runs the Internet Computer. Extremely rare.",
    value: 280,
    weight: 3,
    color: "#7c3aed",
    hardness: 2.1,
    depth: 100,
  },
  [T.CHAIN_FUSION]: {
    name: "Chain Fusion Shard",
    era: "A fragment of cross-chain magic. Bridges worlds.",
    value: 380,
    weight: 4,
    color: "#a78bfa",
    hardness: 2.3,
    depth: 120,
  },
  [T.DRAGGINZ_SCALE]: {
    name: "Dragginz Scale",
    era: "Shed by something ancient that shouldn't be awake.",
    value: 320,
    weight: 3,
    color: "#4ade80",
    hardness: 2.2,
    depth: 110,
  },
  [T.SERAPH_TOKEN]: {
    name: "Seraph Token",
    era: "Allegedly grants 1 million NNS votes. The NNS has not confirmed this.",
    value: 1800,
    weight: 3,
    color: "#fef9c3",
    hardness: 2.1,
    depth: 100,
  },
  [T.VOID_SHARD]: {
    name: "Void Shard",
    era: "A fragment of the ICP dark pool. Traders use it to swap without leaving a trace.",
    value: 4200,
    weight: 4,
    color: "#581c87",
    hardness: 2.6,
    depth: 120,
  },
  [T.DEGEN_CRYSTAL]: {
    name: "Degen Crystal",
    era: "Crystallized hopium. Emits a faint smell of Lambos and leverage trades.",
    value: 420,
    weight: 2,
    color: "#ec4899",
    hardness: 1.7,
    depth: 60,
  },
  [T.QUANTUM_BOB]: {
    name: "Quantum BOB",
    era: "A superposition of BOB and void. Only exists when observed deep in the IC abyss.",
    value: 2800,
    weight: 4,
    color: "#a78bfa",
    hardness: 2.7,
    depth: 100,
  },
  [T.BOB_GENESIS]: {
    name: "BOB Genesis Block",
    era: "The origin of it all",
    value: 21000,
    weight: 10,
    color: "#fde047",
    hardness: 3.5,
    depth: 155,
  },
  [T.LAVA_TUBE]: {
    name: "Lava Tube",
    era: "Ancient geological wonder",
    value: 0,
    weight: 0,
    color: "#FF6600",
    hardness: 0,
    depth: 60,
  },
};

export const BOB_SAVE_KEY = "bob_mining_save";

export const META_PROGRESS_KEY = "bob_meta_progress";

export const UPGRADE_MAX_LEVEL = 5;
export const UPGRADES = [
  {
    key: "hullLevel",
    label: "Hull Plating",
    desc: "Max HP +60/level. Speed -5% per level above 1",
    icon: "🛡",
    costs: [200, 500, 1000, 2000, 4000] as const,
    penalty: "Speed -5% per level above 1",
    buildTag: "DIVER" as const,
    buildColor: "#1d4ed8",
  },
  {
    key: "fuelLevel",
    label: "Fuel Tank",
    desc: "Max Fuel +50/level. Ascent -3% per level above 1",
    icon: "⛽",
    costs: [180, 450, 900, 1800, 3500] as const,
    penalty: "Ascent -3% per level above 1",
    buildTag: "DIVER" as const,
    buildColor: "#1d4ed8",
  },
  {
    key: "cargoLevel",
    label: "Cargo Hold",
    desc: "Cargo capacity +35 per level",
    icon: "📦",
    costs: [200, 500, 1000, 2000, 4000] as const,
    penalty: null,
    buildTag: "PRO" as const,
    buildColor: "#22c55e",
  },
  {
    key: "drillLevel",
    label: "Drill Bit",
    desc: "Drill speed +40% per level",
    icon: "⛏",
    costs: [250, 600, 1200, 2400, 5000] as const,
    penalty: null,
    buildTag: "DIVER" as const,
    buildColor: "#1d4ed8",
  },
  {
    key: "engineLevel",
    label: "Engine",
    desc: "Move speed +25% per level",
    icon: "🔧",
    costs: [200, 500, 1000, 2000, 4200] as const,
    penalty: null,
    buildTag: "RUNNER" as const,
    buildColor: "#06b6d4",
  },
  {
    key: "shieldLevel",
    label: "Energy Shield",
    desc: "Fall/hazard damage -20% per level",
    icon: "⚡",
    costs: [220, 550, 1100, 2200, 4500] as const,
    penalty: null,
    buildTag: "PRO" as const,
    buildColor: "#22c55e",
  },
  {
    key: "radarLevel",
    label: "Deep Radar",
    desc: "Reveals ore on minimap + lore rooms",
    icon: "📡",
    costs: [230, 580, 1150, 2300, 4800] as const,
    penalty: null,
    buildTag: "PRO" as const,
    buildColor: "#22c55e",
  },
  {
    key: "thrusterLevel",
    label: "Afterburner",
    desc: "Upward thrust +18% per level",
    icon: "🚀",
    costs: [210, 520, 1050, 2100, 4200] as const,
    penalty: null,
    buildTag: "RUNNER" as const,
    buildColor: "#06b6d4",
  },
  {
    key: "coolantLevel",
    label: "Drill Coolant",
    desc: "Drill progress +18% per level",
    icon: "❄",
    costs: [200, 490, 980, 1960, 4000] as const,
    penalty: null,
    buildTag: "RUNNER" as const,
    buildColor: "#06b6d4",
  },
];

// ─── BUILD PATH SYNERGY ────────────────────────────────────────────────────────────────
export const BUILD_PATHS = {
  RUNNER: {
    label: "Speed Runner",
    color: "#06b6d4",
    keys: ["engineLevel", "thrusterLevel", "coolantLevel"],
    bonus: "speed_runner",
    bonusDesc: "+15% Move Speed",
  },
  DIVER: {
    label: "Deep Diver",
    color: "#1d4ed8",
    keys: ["hullLevel", "fuelLevel", "drillLevel"],
    bonus: "deep_diver",
    bonusDesc: "+10% Drill Power",
  },
  PRO: {
    label: "Prospector",
    color: "#22c55e",
    keys: ["cargoLevel", "shieldLevel", "radarLevel"],
    bonus: "prospector",
    bonusDesc: "+10% Sell Prices",
  },
} as const;

export const GLOWING_TILES = new Set<number>([
  T.BOB_DUST,
  T.BOB_FLECK,
  T.BOB_FRAGMENT,
  T.BOB_SHARD,
  T.BOB_CHIP,
  T.BOB_CRYSTAL,
  T.BOB_CORE,
  T.BOB_INGOT,
  T.BOB_VEIN,
  T.BOB_SEAM,
  T.NNS_TOKEN,
  T.CHAIN_FUSION,
  T.DRAGGINZ_SCALE,
  T.BOB_GENESIS,
  T.LAVA_TILE,
  T.CRYSTAL_WALL,
  T.SERAPH_TOKEN,
  T.VOID_SHARD,
  T.DEGEN_CRYSTAL,
  T.QUANTUM_BOB,
]);

export const ORE_GLOW_COLORS: Record<number, string> = {
  [T.BOB_DUST]: "#fbbf24",
  [T.BOB_FLECK]: "#22d3ee",
  [T.BOB_FRAGMENT]: "#3b82f6",
  [T.BOB_SHARD]: "#f97316",
  [T.BOB_CHIP]: "#a855f7",
  [T.BOB_CRYSTAL]: "#67e8f9",
  [T.BOB_CORE]: "#f59e0b",
  [T.BOB_INGOT]: "#a3e635",
  [T.BOB_VEIN]: "#fde047",
  [T.BOB_SEAM]: "#c084fc",
  [T.NNS_TOKEN]: "#7c3aed",
  [T.CHAIN_FUSION]: "#a78bfa",
  [T.DRAGGINZ_SCALE]: "#4ade80",
  [T.BOB_GENESIS]: "#fde047",
  [T.SERAPH_TOKEN]: "#fef9c3",
  [T.VOID_SHARD]: "#a855f7",
  [T.DEGEN_CRYSTAL]: "#f472b6",
  [T.QUANTUM_BOB]: "#a78bfa",
};

// Pre-computed tile color cache to avoid per-frame string allocations
export const TILE_COLOR_CACHE: Map<number, string> = new Map();

// Suppress unused import warnings - these are re-exported for consumers
export type { RunModifier, Resource, CargoItem, RunQuest };
